-- SELECT *
-- SELECIONAR TODAS AS LINHAS

SELECT * FROM CCA.`202211`;


-- SELECT COLUMN
-- SELECIONAR TODAS AS LINHAS DA COLUNA ASSESSORIA 

SELECT ASSESSORIA FROM CCA.`202211`;


-- SELECT DISTINCT
-- LISTA DE TODAS AS ASSESSORIAS SEM REPETIÇÃO


SELECT DISTINCT ASSESSORIA FROM CCA.`202211`;

-- ORDER BY
-- MAIORES SALDOS CONTÁBEIS

SELECT DISTINCT CONTRATO, SALDOCONTABIL FROM CCA.`202211`
ORDER BY saldocontabil DESC;

-- LIMIT
-- 5 PRINCIPAIS

SELECT DISTINCT CONTRATO, SALDOCONTABIL FROM CCA.`202211`
ORDER BY saldocontabil DESC 
LIMIT 5;


-- SELECT WHERE
-- RESTRIÇÃO DE PRODUTO

SELECT DISTINCT CONTRATO, SALDOCONTABIL, PRODUTO FROM CCA.`202211`
WHERE PRODUTO = '0410'
ORDER BY saldocontabil DESC 
LIMIT 5;



-- AND OR
-- MAIS RESTRIÇÕES

SELECT DISTINCT CONTRATO, SALDOCONTABIL, PRODUTO, Subproduto FROM CCA.`202211`
WHERE PRODUTO = '0410' AND SUBPRODUTO = '0001'
ORDER BY saldocontabil DESC 
LIMIT 5;



SELECT DISTINCT CONTRATO, SALDOCONTABIL, PRODUTO, Subproduto FROM CCA.`202211`
WHERE PRODUTO = '0410' AND SUBPRODUTO = '0001' OR SUBPRODUTO = '0002'
ORDER BY saldocontabil DESC;



-- IN 

SELECT DISTINCT CONTRATO, SALDOCONTABIL, PRODUTO, Subproduto FROM CCA.`202211`
WHERE PRODUTO = '0410' AND SUBPRODUTO IN ('0001', '0002')
ORDER BY saldocontabil DESC;


-- LIKE

-- INICIA
SELECT DISTINCT ASSESSORIA, CONTRATO, SALDOCONTABIL, PRODUTO, Subproduto FROM CCA.`202211`
WHERE PRODUTO = '0410' AND SUBPRODUTO IN ('0001', '0002') AND ASSESSORIA LIKE 'COBES%'
ORDER BY saldocontabil DESC
LIMIT 5;


-- CONTEM
SELECT DISTINCT ASSESSORIA, CONTRATO, SALDOCONTABIL, PRODUTO, Subproduto FROM CCA.`202211`
WHERE PRODUTO = '0410' AND SUBPRODUTO IN ('0001', '0002') AND ASSESSORIA LIKE '%COBES%'
ORDER BY saldocontabil DESC
LIMIT 5;



-- TERMINA
SELECT DISTINCT ASSESSORIA, CONTRATO, SALDOCONTABIL, PRODUTO, Subproduto FROM CCA.`202211`
WHERE PRODUTO = '0410' AND SUBPRODUTO IN ('0001', '0002') AND ASSESSORIA LIKE '%LTDA'
ORDER BY saldocontabil DESC
LIMIT 5;

-- OPERADORES 

SELECT DISTINCT ASSESSORIA, CONTRATO, SALDOCONTABIL/100, PRODUTO, Subproduto FROM CCA.`202211`
WHERE PRODUTO = '0410' AND SUBPRODUTO IN ('0001', '0002') AND ASSESSORIA LIKE '%LTDA'
ORDER BY saldocontabil DESC
LIMIT 5;


+ 
- 
* 
/
=

>

< 

-- CONTRATO, SALDO , DIAS ATRASO ENTRE 360 E 1080

SELECT DISTINCT CONTRATO, SALDOCONTABIL/100, DIASATRASO FROM CCA.`202211`
WHERE DIASATRASO >=360 AND DIASATRASO <= 1080
ORDER BY saldocontabil DESC;



-- BETWEEN

SELECT DISTINCT CONTRATO, SALDOCONTABIL/100, DIASATRASO FROM CCA.`202211`
WHERE DIASATRASO BETWEEN 360 AND 1080
ORDER BY saldocontabil DESC;


-- ALIAS (AS)

SELECT DISTINCT CONTRATO, 
SALDOCONTABIL/100 AS 'VALOR', 
DIASATRASO FROM CCA.`202211`
WHERE DIASATRASO BETWEEN 360 AND 1080
ORDER BY saldocontabil DESC;

-- WHERE NOT

SELECT DISTINCT ASSESSORIA FROM CCA.`202211`
WHERE NOT ASSESSORIA LIKE 'COBES%';

SELECT DISTINCT ASSESSORIA FROM CCA.`202211`
WHERE NOT ASSESSORIA = 'COBES   ' ;

SELECT DISTINCT ASSESSORIA FROM CCA.`202211`
WHERE ASSESSORIA <> 'COBES       ';


-- LISTA DE ASSESSORIAS NÃO CONTENHA ASSESSORIA COBES




-- OUTRA DEMANDA: 
-- SOMA DO SALDO CONTABIL DE TODOS OS CONTRATOS DAS ASSESSORIAS

SELECT ASSESSORIA, SALDOCONTABIL FROM CCA.`202211`;



-- FALTANDO: SOMA  - AGRUPADA





